import "./globals.css"

import { Inter } from "next/font/google"
import type { Metadata } from "next"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
   title: `Manage Your Team's Project From Anywhere | Trello `,
   description: "Generated by create next app",
   icons: "/assets/trello-icon.svg",
}

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html lang='en'>
         <body className={inter.className}>{children}</body>
      </html>
   )
}
